 services:
  - type: web
    name: my-flask-app
    env: python
    plan: free
    branch: main
    buildCommand: "pip install -r requiremnets.txt"
    startCommand: "gunicorn app:app"
    autoDeploy: false
